name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.0.5
      - run: |
          ./bin/fetch-configlet
          ./bin/configlet lint .
